# Copyright 2025 Espressif Systems (Shanghai) PTE LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import xml.etree.ElementTree as ET
from pathlib import Path

from pics_tool.generate.writer import write_filled

TEMPLATE = """<?xml version='1.0' encoding='utf-8'?>
<!-- Autogenerated header comment - do not lose me -->
<clusterPICS>
  <clusterSide type="Server">
    <attributes>
      <picsItem>
        <itemNumber>OO.S.A0000</itemNumber>
        <feature>OnOff attribute?</feature>
        <status>M</status>
        <support>false</support>
      </picsItem>
      <picsItem>
        <itemNumber>OO.S.A4000</itemNumber>
        <feature>GlobalSceneControl?</feature>
        <status cond="OO.S.F00">M</status>
        <support>false</support>
      </picsItem>
    </attributes>
  </clusterSide>
</clusterPICS>
"""


def test_write_filled_toggles_support_and_preserves_header(tmp_path):
    src = tmp_path / "t.xml"
    src.write_text(TEMPLATE, encoding="utf-8")
    dst = tmp_path / "out.xml"

    count = write_filled(src, dst, {"OO.S.A0000"})
    assert count == 1

    text = dst.read_text(encoding="utf-8")
    assert "do not lose me" in text          # header comment preserved
    assert text.startswith("<?xml")           # xml declaration preserved

    # Structured check: A0000 true, A4000 still false.
    root = ET.parse(str(dst)).getroot()
    support = {pi.find("itemNumber").text: pi.find("support").text
              for pi in root.iter("picsItem")}
    assert support["OO.S.A0000"] == "true"
    assert support["OO.S.A4000"] == "false"


def test_only_support_lines_change(tmp_path):
    src = tmp_path / "t.xml"
    src.write_text(TEMPLATE, encoding="utf-8")
    dst = tmp_path / "out.xml"
    write_filled(src, dst, {"OO.S.A0000", "OO.S.A4000"})

    def non_support(text):
        return [ln for ln in text.splitlines() if "<support>" not in ln]

    assert non_support(TEMPLATE) == non_support(dst.read_text(encoding="utf-8"))


def test_pixit_checklist_written(tmp_path):
    from pics_tool.generate.writer import write_pics

    summary = write_pics("1.6", {0: {"CNET.S", "CNET.S.F00"}}, tmp_path)
    checklist = tmp_path / "PIXIT_CHECKLIST.md"
    assert checklist.exists()
    text = checklist.read_text(encoding="utf-8")
    assert "PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID" in text
    assert "endpoint0" in text
    assert summary.pixits >= 9  # CNET alone carries 9 PIXITs
